---

- name: Install dependence packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - pcre
      - pcre-devel
      - openssl-devel
      - perl
      - gcc
      - make
      - wget

- name: Create user and nginx directory
  shell: |
    useradd nginx
    usermod -s /sbin/nologin nginx
    mkdir -p /GYMBOREE/APP/Nginx
    mkdir -p /GYMBOREE/LOG/Nginx
    mkdir -p /GYMBOREE/BIN/Nginx
    mkdir -p /GYMBOREE/cache/Nginx
    mkdir -p /var/log/nginx
    mkdir -p /var/cache/nginx

- name: Download nginx package
  shell: |
    wget http://nginx.org/download/nginx-1.14.0.tar.gz
    tar xzvf nginx-1.14.0.tar.gz
    cd nginx-1.14.0

- name: Install nginx
  shell: |
    ./configure --prefix=/GYMBOREE/APP/Nginx --sbin-path=/usr/sbin/nginx --conf-path=/GYMBOREE/APP/Nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'
    make
    make install
  ignore_errors: true

- name: Add  nginx to system service
  template:
    src: "nginx.service"
    dest: "/usr/lib/systemd/system/nginx.service"

- name: Start nginx
  shell: |
    systemctl daemon-reload
    systemctl start nginx
    systemctl status nginx

- name: Create link to manage more convenience
  shell: |
    ln -s /GYMBOREE/APP/Nginx /etc/nginx
    ln -s /var/log/nginx /GYMBOREE/LOG/Nginx
    ln -s /usr/sbin/nginx /GYMBOREE/BIN/Nginx
    ln -s /var/cache/nginx/ /GYMBOREE/cache/Nginx
  
