---

- name: Download zabbix agent 
  shell: |
    rpm --import /etc/pki/rpm-gpg/RPM*
    rpm -i https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
  ignore_errors: True

- name: Install zabbix agent
  yum: pkg=zabbix-agent state=latest

- name: Modify zabbix_agentd.conf
  template:
    src: "zabbix_agentd_offline.conf"
    dest: "/etc/zabbix/zabbix_agentd.conf"
    backup: yes

- name: Restart zabbix agent
  service: name=zabbix-agent state=restarted

- name: Start zabbix agent when start machine
  shell: systemctl enable zabbix-agent
