---

- name: Download zabbix agent 
  shell: |
    rpm --import /etc/pki/rpm-gpg/RPM*
    rpm -i https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
  ignore_errors: True

- name: Install zabbix agent
  yum: pkg=zabbix-agent state=latest

- name: Modify zabbix_agentd.conf
  template:
    src: "zabbix_agentd_online.conf"
    dest: "/etc/zabbix/zabbix_agentd.conf"
    backup: yes

- name: Make zabbix modules dir
  shell: mkdir /etc/zabbix/modules
  ignore_errors: True

- name: Added zabbix docker module
  copy:
    src: "roles/zabbix_agent/templates/zabbix_module_docker.so"
    dest: "/etc/zabbix/modules/zabbix_module_docker.so"
  ignore_errors: True

- name: Yum install docker
  shell: |
    yum remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine
    yum install -y yum-utils device-mapper-persistent-data lvm2 
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum-config-manager --enable docker-ce-nightly
    yum-config-manager --enable docker-ce-test
    yum-config-manager --disable docker-ce-nightly
    yum install -y docker-ce docker-ce-cli containerd.io

- name: Start docker service
  service: name=docker state=started

- name: Enable docker service
  shell: systemctl enable docker

- name: Eable the docker accounting 
  shell: |
    systemctl set-property docker.service MemoryAccounting=yes
    systemctl set-property docker.service CPUAccounting=yes
    systemctl set-property docker.service BlockIOAccounting=yes
    
- name: Restart zabbix agent
  service: name=zabbix-agent state=restarted

- name: Start zabbix agent when start machine
  shell: systemctl enable zabbix-agent
